"""init_all_tables

Revision ID: 0a8658517ccf
Revises: 
Create Date: 2026-03-26 17:26:42.585900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a8658517ccf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age_rumor_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='统计ID'),
    sa.Column('age_group', sa.String(length=20), nullable=False, comment='年龄段：0-18/19-25/26-35/36-45/46+'),
    sa.Column('rumor_related_count', sa.Integer(), nullable=False, comment='相关谣言数量'),
    sa.Column('stat_date', sa.Date(), nullable=False, comment='统计日期'),
    sa.PrimaryKeyConstraint('id'),
    comment='年龄段谣言统计',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_age_group', 'age_rumor_stats', ['age_group', sa.literal_column('rumor_related_count DESC')], unique=False)
    op.create_table('area_rumor_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='统计ID'),
    sa.Column('province', sa.String(length=30), nullable=False, comment='省份'),
    sa.Column('city', sa.String(length=30), nullable=False, comment='城市'),
    sa.Column('rumor_count', sa.Integer(), nullable=False, comment='该地区谣言总量'),
    sa.Column('stat_date', sa.Date(), nullable=False, comment='统计日期'),
    sa.PrimaryKeyConstraint('id'),
    comment='地区谣言分布统计',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_province', 'area_rumor_stats', ['province', sa.literal_column('rumor_count DESC')], unique=False)
    op.create_table('ranking_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='配置ID'),
    sa.Column('rank_name', sa.String(length=50), nullable=False, comment='排行榜名称'),
    sa.Column('rank_type', sa.Enum('heat', 'confirmed'), nullable=False, comment='热度排行/已证实谣言'),
    sa.Column('refresh_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='排行榜配置',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rumors',
    sa.Column('rumor_id', sa.Integer(), autoincrement=True, nullable=False, comment='谣言ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='谣言标题/核心内容'),
    sa.Column('content', sa.Text(), nullable=False, comment='谣言完整描述'),
    sa.Column('refute_content', sa.Text(), nullable=False, comment='官方辟谣内容'),
    sa.Column('official_source', sa.String(length=100), nullable=False, comment='官方来源'),
    sa.Column('official_link', sa.String(length=300), nullable=False, comment='官方辟谣链接'),
    sa.Column('publish_time', sa.DateTime(), nullable=False, comment='官方发布时间'),
    sa.Column('heat_score', sa.Integer(), nullable=False, comment='热度分数'),
    sa.Column('upload_count', sa.Integer(), nullable=False, comment='被用户上传次数'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='总浏览量'),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('rumor_id'),
    comment='权威辟谣主谣言表',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_heat_score', 'rumors', [sa.literal_column('heat_score DESC')], unique=False)
    op.create_index('idx_upload_count', 'rumors', [sa.literal_column('upload_count DESC')], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=100), nullable=False, comment='密码（加密存储）'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='邮箱'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='手机号'),
    sa.Column('age', sa.Integer(), nullable=False, comment='年龄'),
    sa.Column('gender', sa.Enum('男', '女', '未知'), nullable=False, comment='性别'),
    sa.Column('province', sa.String(length=30), nullable=False, comment='省份'),
    sa.Column('city', sa.String(length=30), nullable=False, comment='城市'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='注册时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('status', sa.Enum('正常', '禁用'), nullable=False, comment='账号状态'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    comment='用户表',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_age', 'users', ['age'], unique=False)
    op.create_index('idx_province', 'users', ['province'], unique=False)
    op.create_table('rumor_interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='统计ID'),
    sa.Column('rumor_id', sa.Integer(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False, comment='统计日期'),
    sa.Column('daily_upload', sa.Integer(), nullable=False, comment='当日上传量'),
    sa.Column('daily_view', sa.Integer(), nullable=False, comment='当日浏览量'),
    sa.ForeignKeyConstraint(['rumor_id'], ['rumors.rumor_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='谣言每日统计数据（绘图用）',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_date', 'rumor_interactions', ['stat_date'], unique=False)
    op.create_table('user_browse_records',
    sa.Column('record_id', sa.Integer(), autoincrement=True, nullable=False, comment='记录ID'),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rumor_id', sa.Integer(), nullable=False),
    sa.Column('browse_time', sa.DateTime(), nullable=False, comment='浏览时间'),
    sa.ForeignKeyConstraint(['rumor_id'], ['rumors.rumor_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id'),
    comment='用户浏览记录',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_user_time', 'user_browse_records', ['user_id', sa.literal_column('browse_time DESC')], unique=False)
    op.create_table('user_upload_rumors',
    sa.Column('upload_id', sa.Integer(), autoincrement=True, nullable=False, comment='上传ID'),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('upload_content', sa.Text(), nullable=False, comment='用户上传的原始文本'),
    sa.Column('merged_rumor_id', sa.Integer(), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=False, comment='上传时间'),
    sa.Column('status', sa.Enum('待合并', '已合并', '无效'), nullable=False, comment='处理状态'),
    sa.ForeignKeyConstraint(['merged_rumor_id'], ['rumors.rumor_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('upload_id'),
    comment='用户上传谣言记录表',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_merged', 'user_upload_rumors', ['merged_rumor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_merged', table_name='user_upload_rumors')
    op.drop_table('user_upload_rumors')
    op.drop_index('idx_user_time', table_name='user_browse_records')
    op.drop_table('user_browse_records')
    op.drop_index('idx_date', table_name='rumor_interactions')
    op.drop_table('rumor_interactions')
    op.drop_index('idx_province', table_name='users')
    op.drop_index('idx_age', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_upload_count', table_name='rumors')
    op.drop_index('idx_heat_score', table_name='rumors')
    op.drop_table('rumors')
    op.drop_table('ranking_config')
    op.drop_index('idx_province', table_name='area_rumor_stats')
    op.drop_table('area_rumor_stats')
    op.drop_index('idx_age_group', table_name='age_rumor_stats')
    op.drop_table('age_rumor_stats')
    # ### end Alembic commands ###
